### ISSUE TITLE
osm files

### ISSUE THREAD

**Issue by mtabdar** [openstreetmap/leaflet-osm#24]
hi,
i wonder if it is possible to load .osm file into a leaflet map using this js?

**Comment by tomhughes** [comment]
No it's not - this helps with configuring the tile layers that are shown on the OSM site.

**Comment by tomhughes** [comment]
Sorry I'm wrong - the data layer support is in this module as well, so yes you can - see https://github.com/openstreetmap/leaflet-osm#data-layer for an example.

**Comment by mtabdar** [comment]
thanks for the quick reply.
unfortunately i could not make it work. 
let me explain my question: i have an osm file (exported from openstreetmaps site) and want to show it on a leaflet map and i am not connected to web.

**Comment by tomhughes** [comment]
It's fairly simple - you take the XML and call:

```
var layer = new L.OSM.DataLayer(xml).addTo(map);
```

How you load the XML into the `xml` variable is up to you - that is a general "how do I write javascript" question and nothing specific to this module.
