### ISSUE TITLE
Allow loading dark tiles

### ISSUE THREAD

**Issue by hlfan** [openstreetmap/leaflet-osm#42]
Implementing dark mode tiles in https://github.com/openstreetmap/openstreetmap-website/issues/5328 requires expanding the layer definitions in leaflet-osm.js.
~~A possible solution is to add suffixes in the URLs based on a flag in the options.
For the current two layers that have dark mode variants, this could be achieved by adapting a few keys in the options objects.~~
Updating the tests would also be required.

**Comment by AntonKhorev** [comment]
Why can't their dark variants have another url like https://github.com/openstreetmap/openstreetmap-website/pull/4777/files#diff-4fe14e869cf17b068e1bea009a55b094fed13f0cad85337cf4769f32b40a01b5R262 ?

**Comment by tomhughes** [comment]
That does seem like a better solution to me.

**Comment by hlfan** [comment]
Yes! This is much better!

**Comment by hlfan** [comment]
Leaving this open as the code from the website repo may be propagated here too when an implementation gets merged.

**Comment by hlfan** [comment]
Closing in favor of a more modular solution as in https://github.com/openstreetmap/leaflet-osm/commit/ebfaf22426c265aaf3f401d70ffd02ca920623c9.
